name: Build and Push

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write  # Permite leer el contenido del repositorio
  actions: write  # Permite ejecutar flujos de trabajo de Actions
  pull-requests: write
  packages: write
jobs:

  reusable_workflow_call:
    name: Build and Push
    uses: fhidalgoc-org/.github/.github/workflows/blank.yml@main
    with:
      repository: ${{ github.repository }}
      username: fhidalgoc
    secrets:
      personal_access_token: ${{ secrets.GITHUB_TOKEN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_PASSWORD }}


