name: Octo Organization CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read  # Permite leer el contenido del repositorio
  actions: write  # Permite ejecutar flujos de trabajo de Actions

jobs:
  reusable_workflow_call:
    uses: fhidalgoc-org/.github/.github/workflows/blank.yml@main
    with:
      name: hello_from_template
      personal_access_token: ${{ github.token }}


