name: Octo Organization CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: fhidalgoc-org/.github/.github/workflows/blank.yml@main
        name: run reusable workflow
        with:
          name: hello_from_template
          personal_access_token: ${{ secrets.GITHUB_TOKEN }}
