name: Build and Push

on:
  push:
    # branches: [ "main" ]
  pull_request:
    # branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write  # Permite leer el contenido del repositorio
  actions: write  # Permite ejecutar flujos de trabajo de Actions
  pull-requests: write

jobs:
  reusable_workflow_call:
    name: Build and Push
    uses: fhidalgoc-org/.github/.github/workflows/blank.yml@main
    with:
      branch: ${{ github.ref_name }}
    # secrets:
    #   personal_access_token: ${{ github.token }}


